package main;

import jdbc.DbManager;

public class test {
	private DbManager db;

	public test() {
		db = new DbManager();
		db.setData("-- MySQL Script generated by MySQL Workbench\r\n" + "-- Sun Dec 18 20:48:02 2022\r\n"
				+ "-- Model: New Model    Version: 1.0\r\n" + "-- MySQL Workbench Forward Engineering\r\n" + "\r\n"
				+ "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\r\n"
				+ "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\r\n"
				+ "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n" + "-- Schema DMUP_DB\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "DROP SCHEMA IF EXISTS `DMUP_DB` ;\r\n" + "\r\n"
				+ "-- -----------------------------------------------------\r\n" + "-- Schema DMUP_DB\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE SCHEMA IF NOT EXISTS `DMUP_DB` DEFAULT CHARACTER SET utf8 ;\r\n" + "USE `DMUP_DB` ;\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n"
				+ "-- Table `DMUP_DB`.`user`\r\n" + "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `DMUP_DB`.`user` (\r\n" + "  `u_no` INT NOT NULL AUTO_INCREMENT,\r\n"
				+ "  `u_name` VARCHAR(45) NULL,\r\n" + "  `u_address` VARCHAR(45) NULL,\r\n"
				+ "  `u_number` VARCHAR(45) NULL,\r\n" + "  PRIMARY KEY (`u_no`))\r\n" + "ENGINE = InnoDB;\r\n" + "\r\n"
				+ "\r\n" + "SET SQL_MODE=@OLD_SQL_MODE;\r\n" + "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\r\n"
				+ "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;");
	}

	public static void main(String[] args) {
		new test();
	}
}
